export enum KafkaTopics {
    USER_CREATED = 'user-created',
    JOB_VALIDATION_REQUESTED = 'job-validation-request',
    JOB_STATUS_UPDATED = 'job-status-updated',
    JOB_POST_ACCEPTED = 'job-post-accepted',
    JOB_POST_REJECTED = 'job-post-rejected',
    JOB_APPLIED = 'job-applied',
    JOB_APPLICATION_ACCEPTED = 'job-application-accepted',
    JOB_APPLICATION_REJECTED = 'job-application-rejected',
    JOB_APPLICATION_VIEWED = 'job-application-viewed',
    JOB_APPLICATION_VIEW_UPDATED = 'job-application-viewed-updated',
    RESUME_COMMENTED = 'RESUME_COMMENTED',
    FOLLOW_REQUESTED = 'follow-requested',
    FOLLOW_ACCEPTED = 'follow-accepted',
    FOLLOW_REJECTED = 'follow-rejected',
    INTERVIEW_SCHEDULED = 'interview-scheduled',
    INTERVIEW_SCHEDULE_ACCEPTED = 'interview-schedule-accepted',
    INTERVIEW_SCHEDULE_REJECTED = 'interview-schedule-rejected',
    INTERVIEW_SCHEDULE_CANCELLLED = 'interview-schedule-cancelled',
    JOB_OFFERED = 'job-offered',
    JOB_OFFER_ACCEPTED = 'job-offer-accepted',
    JOB_OFFER_REJECTED = 'job-offer-rejected',
}
