name: Publish Common Library

on:
  push:
    branches:
      - main
    paths:
      - 'common/**'
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with npm
        run: echo "authToken=${{ secrets.NPM_TOKEN }}"

      - name: Install dependencies
        run: |
          cd common
          npm install

      - name: Publish to npm
        run: |
          cd common
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
